apiVersion: v1
kind: Service
metadata:
  name: multi-client-service
spec:
  type: NodePort
  selector:
    app: multi-client-app
  ports:
  - nodePort: 31111
    port: 5000
    targetPort: 80

--- 

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: multi-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-client-app
  template:
    metadata:
      labels:
        app: multi-client-app
    spec:
      containers:
      - name: multi-client-app
        image: ashutoshpandey/kube-multi-client:v1
        ports:
        - containerPort: 80
