apiVersion: v1
kind: Service
metadata:
  name: kubemultitestclientservice
spec:
  type: NodePort
  selector:
    app: kubemultitestclient
  ports:
  - nodePort: 31111
    port: 5000
    targetPort: 80
---    
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: kubemulticlientdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubemultitestclient
  template:
    metadata:
      labels:
        app: kubemultitestclient
    spec:
      containers:
      - name: kubemultitestclient
        image: ashutoshpandey/kube-multi-client:v1
        ports:
        - containerPort: 80
