apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubemulticlient
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: kubemulticlient
        image: ashutoshpandey/kubemultiserver:v1
        ports:
        - containerPort: 3000