apiVersion: v1
kind: Service
metadata:
  name: kubemultitestserv
  labels:
    app: kubemultitest
spec:
  type: NodePort
  selector:
    app: kubemultitest
  ports:
  - nodePort: 31112
    port: 3000
    targetPort: 3000
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubemultitestdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubemultitest
  template:
    metadata:
      labels:
        app: kubemultitest
    spec:
      containers:
      - name: kubemultitest
        image: ashutoshpandey/kube-multi-server:v1.1
        ports:
        - containerPort: 3000