apiVersion: v1
kind: Service
metadata:
  name: multi-server-service
  labels:
    app: multi-server-app
spec:
  type: NodePort
  selector:
    app: multi-server-app
  ports:
  - nodePort: 31112
    port: 3000
    targetPort: 3000

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-server-app
  template:
    metadata:
      labels:
        app: multi-server-app
    spec:
      containers:
      - name: multi-server-app
        image: ashutoshpandey/kube-multi-server:v2
        ports:
        - containerPort: 3000