apiVersion: v1
kind: Service
metadata:
  name: multi-server-service
  namespace: kube-multi-test
  labels:
    app: multi-server-app
spec:
  type: NodePort
  selector:
    app: multi-server-app
  ports:
    - nodePort: 31112
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-server-deployment
  namespace: kube-multi-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-server-app
  template:
    metadata:
      labels:
        app: multi-server-app
    spec:
      containers:
        - name: multi-server-app
          image: ashutoshpandey/kube-multi-server:v3
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: dbhost
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: dbname
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: dbport
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
